- Cargo.lock
- contracts/liquidity_hub/vault-network/vault/Cargo.toml
- contracts/liquidity_hub/vault-network/vault_factory/Cargo.toml
- contracts/liquidity_hub/vault-network/vault_factory/schema/execute_msg.json
- contracts/liquidity_hub/vault-network/vault_factory/schema/query_msg.json
- packages/vault-network/src/vault.rs
- packages/vault-network/src/vault_factory.rs
- packages/white-whale/src/fee.rs
The vault network had structs that were not snake cased, which wasn't following the standard normally used. This PR fixes this, making it consistent with the rest of the project.
#42 
---
> fix: snake case on vault network structs

- Cargo.lock
- contracts/liquidity_hub/fee_collector/Cargo.toml
- contracts/liquidity_hub/fee_collector/examples/schema.rs
- contracts/liquidity_hub/fee_collector/schema/collect_fees_for.json
- contracts/liquidity_hub/fee_collector/schema/contract.json
- contracts/liquidity_hub/fee_collector/schema/contract_type.json
- contracts/liquidity_hub/fee_collector/schema/query_fees_for.json
- contracts/liquidity_hub/fee_collector/schema/query_msg.json
- contracts/liquidity_hub/fee_collector/src/contract.rs
- contracts/liquidity_hub/fee_collector/src/msg.rs
- contracts/liquidity_hub/fee_collector/src/queries.rs
- contracts/liquidity_hub/fee_collector/src/tests/integration.rs
DRAFT. I started working on the fee_collector queries about collected and accrued fees. 
I started with the later one. Is this right direction?
#47 
---
> #47 | accrued fees query

- scripts/deployment/deploy_env/mainnets/chihuahua.env
- scripts/deployment/deploy_liquidity_hub.sh
Add Chihuahua env variables to the deployment script.
---
> ci: add chihuahua mainnet to deployment script

- packages/terraswap/src/factory.rs
needed by https://github.com/White-Whale-Defi-Platform/pool-network/pull/11
---
> feat(terraswap): factory remove pair ExecuteMsg

- scripts/deployment/deploy_env/testnets/injective.env
- scripts/deployment/deploy_env/testnets/injective_base.env
Adding details for injective testnet.
---
> ci: add injective testnet details for deployment

- README.md
This PR adds information about how to build and deploy migaloo core on the main readme file.
---
> docs: add info about the deployment scripts on the readme file

- README.md
This PR adds information about deployed Migaloo contracts across chains. It also adds information about the audit.
---
> docs: improve main readme info

- scripts/deployment/deploy_env/base_chihuahua.env
- scripts/deployment/deploy_env/chain_env.sh
- scripts/deployment/deploy_env/mainnets/juno.env
- scripts/deployment/deploy_env/mainnets/terra.env
- scripts/deployment/migrate_liquidity_hub.sh
This PR adds a migrate script to be used as a companion when doing migrations.
---
> ci: add migrate script

- README.md
Replaced faulty link in README.md
> docs: replaced faulty link

- scripts/deployment/deploy_env/chain_env.sh
- scripts/deployment/deploy_env/mainnets/migaloo.env
- scripts/deployment/deploy_env/testnets/migaloo.env
This PR adds the migaloo mainnet and testnet env config for deployments.
---
> ci: add migaloo chain

- scripts/deployment/deploy_env/chain_env.sh
- scripts/deployment/deploy_env/mainnets/orai.env
This PR adds oraichain to the deploy script.
---
> ci: oraichain env info

- contracts/liquidity_hub/fee_distributor/src/error.rs
> fix: replace fees with rewards

- contracts/liquidity_hub/pool-network/stableswap_3pool/sim/src/lib.rs
- contracts/liquidity_hub/pool-network/terraswap_factory/src/commands.rs
- contracts/liquidity_hub/pool-network/terraswap_factory/src/error.rs
- contracts/liquidity_hub/vault-network/vault_router/schema/vault_router.json
This PR implements the changes to fix audit issue#16 (Incorrect error name) reported by SCV
---
> Fix/audit incorrect error name #16

- contracts/liquidity_hub/fee_collector/src/contract.rs
Skip sending fees to the fee distributor when creating a new epoch if there were no fees aggregated on the fee collector. This prevents errors due to 0 coins sent in the BankMsg.
---
> Fix epoch creation 

- contracts/liquidity_hub/pool-network/terraswap_pair/src/commands.rs
Fixes the function description on the pool swap function.
---
> fix(pool): improve function description on swap function

- contracts/liquidity_hub/fee_collector/src/tests/integration.rs
- contracts/liquidity_hub/fee_distributor/src/commands.rs
- contracts/liquidity_hub/fee_distributor/src/error.rs
- contracts/liquidity_hub/fee_distributor/src/helpers.rs
- contracts/liquidity_hub/fee_distributor/src/tests/epoch.rs
- contracts/liquidity_hub/fee_distributor/src/tests/robot.rs
- contracts/liquidity_hub/fee_distributor/src/tests/testing.rs
This PR makes the maximum grace period to be 30 on the fee distributor contract.
---
> chore: improvement on fee distributor grace period

- contracts/liquidity_hub/whale_lair/src/commands.rs
- contracts/liquidity_hub/whale_lair/src/helpers.rs
- contracts/liquidity_hub/whale_lair/src/state.rs
This PR makes some improvements to the whale lair based on internal feedback. 
---
> refactor(whale_lair): make code easier to read

- Cargo.lock
- contracts/liquidity_hub/fee_collector/src/tests/integration.rs
- contracts/liquidity_hub/fee_distributor/Cargo.toml
- contracts/liquidity_hub/fee_distributor/src/commands.rs
- contracts/liquidity_hub/fee_distributor/src/contract.rs
- contracts/liquidity_hub/fee_distributor/src/tests/robot.rs
- packages/white-whale/src/fee_distributor.rs
This PR adds changing the epoch config in the update config message of the fee distributor contract.
---
> fix(fee_distributor): add epoch config parameter on update config message

- contracts/liquidity_hub/pool-network/terraswap_factory/src/migrations.rs
This PR fixes some missing pieces when migrating the pool factory to v120.
---
> fix(pool_factory): fix v120 migration structs

- scripts/deployment/deploy_liquidity_hub.sh
- scripts/deployment/deploy_pool.sh
This PR adjusts the deployment scripts to be compatible with the latest release v1.3.0.
---
> chore: adjust deployment scripts to match messages from the latest release

- scripts/deployment/deploy_env/mainnets/chihuahua.env
- scripts/deployment/deploy_env/mainnets/comdex.env
- scripts/deployment/deploy_env/mainnets/injective.env
Had these changes locally from a few deployments figured it'd be good to merge em in
Just updates RPCS, some were ded, some were slower. I think we now nearly use all WW RPCs which is good 
---
> chore(rpc): Update deployment script envs to use in-house RPCs

- contracts/liquidity_hub/pool-network/incentive/schema/incentive.json
- contracts/liquidity_hub/pool-network/incentive/schema/raw/query.json
- contracts/liquidity_hub/pool-network/incentive/schema/raw/response_to_current_epoch_rewards_share.json
- contracts/liquidity_hub/pool-network/incentive/schema/raw/response_to_global_weight.json
- contracts/liquidity_hub/pool-network/incentive/src/contract.rs
- contracts/liquidity_hub/pool-network/incentive/src/error.rs
- contracts/liquidity_hub/pool-network/incentive/src/execute/claim.rs
- contracts/liquidity_hub/pool-network/incentive/src/queries/get_global_weight.rs
- contracts/liquidity_hub/pool-network/incentive/src/queries/get_rewards_share.rs
- contracts/liquidity_hub/pool-network/incentive/src/queries/mod.rs
- contracts/liquidity_hub/pool-network/incentive/src/tests/integration.rs
- contracts/liquidity_hub/pool-network/incentive/src/tests/suite.rs
- packages/white-whale/src/pool_network/incentive.rs
This PR addssome queries needed by the frontend to integrate incentives properly.
---
> feat(incentives): add query for weights and rewards

- Cargo.lock
- contracts/liquidity_hub/fee_collector/Cargo.toml
- contracts/liquidity_hub/fee_distributor/src/migrations.rs
- contracts/liquidity_hub/whale_lair/src/queries.rs
> fix: fix migration on fee distributor

- .github/workflows/ci-test-fmt-check.yaml
- .github/workflows/pr-convcom-check.yaml
Also update to latest stable rust
Fixes #86 
Fixes #144 
Fixes #73 
---
> fix(cache): Replace actions/cache with rust-cache and update to stable rust

- .github/workflows/ci-test-fmt-check.yaml
> fix(compile): Rm extra compile job, test build. 40% improvement

- contracts/liquidity_hub/pool-network/terraswap_router/schema/raw/query.json
- contracts/liquidity_hub/pool-network/terraswap_router/schema/raw/response_to_swap_routes.json
- contracts/liquidity_hub/pool-network/terraswap_router/schema/terraswap-router.json
- contracts/liquidity_hub/pool-network/terraswap_router/src/contract.rs
- contracts/liquidity_hub/pool-network/terraswap_router/src/testing/tests.rs
- packages/white-whale/src/pool_network/router.rs
> feat(SwapRoutes): Add query for all swap routes on router and test

- scripts/deployment/create_incentives.sh
This PR adds a script to create incentives on a liquidity hub. Handy for deploying incentives in a satellite market for first time.  
---
> ci: add script to create incentives on a liquidity hub

- .gitignore
- Cargo.lock
- contracts/liquidity_hub/epoch-manager/Cargo.toml
- contracts/liquidity_hub/epoch-manager/src/bin/schema.rs
- contracts/liquidity_hub/epoch-manager/src/commands.rs
- contracts/liquidity_hub/epoch-manager/src/contract.rs
- contracts/liquidity_hub/epoch-manager/src/error.rs
- contracts/liquidity_hub/epoch-manager/src/queries.rs
- contracts/liquidity_hub/epoch-manager/src/state.rs
- contracts/liquidity_hub/epoch-manager/tests/common.rs
- contracts/liquidity_hub/epoch-manager/tests/config.rs
- contracts/liquidity_hub/epoch-manager/tests/epoch.rs
- contracts/liquidity_hub/epoch-manager/tests/hooks.rs
- contracts/liquidity_hub/epoch-manager/tests/instantiate.rs
- contracts/liquidity_hub/vault-manager/tests/common/suite.rs
- packages/white-whale/Cargo.toml
- packages/white-whale/src/common.rs
- packages/white-whale/src/epoch_manager/epoch_manager.rs
- packages/white-whale/src/epoch_manager/hooks.rs
- packages/white-whale/src/migrate_guards.rs
This PR adds tests to the epoch manager contract.
---
> Add tests to epoch manager

- .github/workflows/release-artifacts-on-tag.yaml
- scripts/check_artifacts_size.sh
- scripts/get_artifacts_versions.sh
This PR modifies the ci action executed when creating tags, so that it appends the artifact versions to the release.
---
> ci: add artifact versions to github releases

- .github/workflows/release-artifacts-on-tag.yaml
This PR fixes the github action for building release artifacts.
---
> ci: fix release artifacts ci action

- contracts/liquidity_hub/pool-network/terraswap_factory/src/contract.rs
This PR fixes the condition checked in the pool factory to migrate to version 1.2.0.
---
> chore: fix pool factory migration to 1.2.0 condition

- Cargo.toml
- justfile
- scripts/build_release.sh
- scripts/build_schemas.sh
- scripts/check_artifacts_size.sh
- scripts/deployment/create_incentives.sh
- scripts/deployment/deploy_env/chain_env.sh
- scripts/deployment/deploy_liquidity_hub.sh
- scripts/deployment/deploy_pool.sh
- scripts/deployment/deploy_test_token.sh
- scripts/deployment/deploy_vault.sh
- scripts/deployment/extract_pools.sh
- scripts/deployment/extract_vaults.sh
- scripts/deployment/ibc_denoms.sh
- scripts/deployment/migrate_incentives.sh
- scripts/deployment/migrate_liquidity_hub.sh
- scripts/deployment/provide_liquidity.sh
- scripts/deployment/wallet_importer.sh
- scripts/get_artifacts_versions.sh
- scripts/hooks/pre-commit.sh
- scripts/testing/test_liquidity_hub.sh
- scripts/utils/crate_versions.sh
This PR fixes the build_release script for osmosis (considering the name change of the white-whale-std package) and also adds a just rule for formatting bash files.
---
> ci: fix and format bash scripts

- .github/workflows/release-artifacts-on-tag.yaml
ci: Specify body_path with artifact_Versions.txt on release to print the new contract versions
Needs testing with a release
---
> Add new contract artifact versions to release body 

- Cargo.lock
- contracts/liquidity_hub/fee_distributor/Cargo.toml
- contracts/liquidity_hub/fee_distributor/src/contract.rs
- contracts/liquidity_hub/fee_distributor/src/migrations.rs
This PR is a hotfix for the osmosis deployment.
---
> chore: forward fees from first epoch to the upcoming one

- scripts/deployment/deploy_env/mainnets/sei.env
This PR changes the `CHAIN-ID` on the `sei.env` file as it was incorrect.
---
> fix(scripts): rename CHAIN-ID on sei.env

- Cargo.lock
- contracts/liquidity_hub/fee_collector/Cargo.toml
- contracts/liquidity_hub/fee_collector/src/commands.rs
- contracts/liquidity_hub/fee_collector/src/tests/integration.rs
- contracts/liquidity_hub/pool-network/stableswap_3pool/Cargo.toml
- contracts/liquidity_hub/pool-network/stableswap_3pool/src/commands.rs
- contracts/liquidity_hub/pool-network/terraswap_pair/Cargo.toml
- contracts/liquidity_hub/pool-network/terraswap_pair/src/commands.rs
- contracts/liquidity_hub/pool-network/terraswap_pair/src/tests/protocol_fees.rs
- contracts/liquidity_hub/pool-network/terraswap_pair/src/tests/swap.rs
This ensures there won't be any possible errors when creating epochs, which could in some edge cases occur.
---
> chore: add minimum collectable and aggregable balances

- Cargo.lock
- Cargo.toml
- contracts/liquidity_hub/fee-distributor-mock/Cargo.toml
- contracts/liquidity_hub/fee_collector/Cargo.toml
- contracts/liquidity_hub/fee_distributor/Cargo.toml
- contracts/liquidity_hub/pool-network/frontend_helper/Cargo.toml
- contracts/liquidity_hub/pool-network/incentive/Cargo.toml
- contracts/liquidity_hub/pool-network/incentive_factory/Cargo.toml
- contracts/liquidity_hub/pool-network/stableswap_3pool/Cargo.toml
- contracts/liquidity_hub/pool-network/terraswap_factory/Cargo.toml
- contracts/liquidity_hub/pool-network/terraswap_pair/Cargo.toml
- contracts/liquidity_hub/pool-network/terraswap_router/Cargo.toml
- contracts/liquidity_hub/pool-network/terraswap_token/Cargo.toml
- contracts/liquidity_hub/vault-network/vault/Cargo.toml
- contracts/liquidity_hub/vault-network/vault_factory/Cargo.toml
- contracts/liquidity_hub/vault-network/vault_router/Cargo.toml
- contracts/liquidity_hub/whale_lair/Cargo.toml
- packages/white-whale-std/Cargo.toml
- packages/white-whale-testing/Cargo.toml
This patches cosmwasm-std.
---
> fix: bump cosmwasm-std

- Cargo.lock
- Cargo.toml
- packages/white-whale-std/Cargo.toml
- packages/white-whale-std/src/coin.rs
- packages/white-whale-std/src/pool_network/swap.rs
Prepare `white-whale-std` package for V2.
---
> chore: prepare the std package for v2
