White-Whale-Defi-Platform/white-whale-core

Cargo.lock
contracts/liquidity_hub/vault-network/vault_factory/Cargo.toml
contracts/liquidity_hub/vault-network/vault_factory/schema/execute_msg.json
contracts/liquidity_hub/vault-network/vault_factory/src/contract.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/update_config.rs
packages/vault-network/src/vault_factory.rs

The vault factory uses a token and a vault code id to create vaults. However, those parameters are not modifiable once the vault factory is created, so if you migrate the vault or token contract you basically need to create a new vault for that, which isn't optimal.
#41 
---

fix: make vault and token id params updatable on vault factory

---

scripts/build_release.sh
scripts/check_artifacts_size.sh

This PR adds a script to check the generated wasm artifact files size, fails if it goes above the given threshold, default 600 kB. The script runs after generated the wasm files with `scripts/build_release.sh`
#40 
---

ci: add script to check wasm artifacts size

---

Cargo.lock
contracts/liquidity_hub/vault-network/vault_factory/Cargo.toml
contracts/liquidity_hub/vault-network/vault_factory/schema/execute_msg.json
contracts/liquidity_hub/vault-network/vault_factory/src/contract.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/migrate_vaults.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/mod.rs
contracts/liquidity_hub/vault-network/vault_factory/src/tests/store_code.rs
packages/vault-network/src/vault_factory.rs

This PR adds a message on the vault factory contract to migrate its vaults. The message allows you to migrate either one (given) vault or all of them.
#49 
---

feat: migrate vaults from vault factory

---

Cargo.toml
scripts/build_schemas.sh

This fixes the bug for generating the schemas for the fee collector contract. Turns out the label being checked was wrong.
#36 
---

fix: fee_collector schemas generation

---

Cargo.lock
Cargo.toml
contracts/liquidity_hub/vault-network/vault/Cargo.toml
contracts/liquidity_hub/vault-network/vault/src/contract.rs
contracts/liquidity_hub/vault-network/vault/src/error.rs
contracts/liquidity_hub/vault-network/vault/src/execute/callback/after_trade.rs
contracts/liquidity_hub/vault-network/vault/src/execute/deposit.rs
contracts/liquidity_hub/vault-network/vault/src/execute/flash_loan.rs
contracts/liquidity_hub/vault-network/vault/src/state.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/update_vault_config.rs

During a flash-loan, if a user deposits funds, they are able to pay off their loan as well as claim the flash-loaned funds as their own. To solve this, we disable deposits while a user is flash-loaning.
---

Fix re-entrancy attack in vault deposit

---

contracts/liquidity_hub/vault-network/vault/src/error.rs
contracts/liquidity_hub/vault-network/vault/src/execute/callback/after_trade.rs

Currently the error message is unhelpful as it displays the old balance before the loan occurred, and the required amount. It would be helpful for errors if they displayed the balance the contract got to, so we can see the difference between what was received as output, and what was required.
---

Make Vault NegativeProfit error display current balance

---

scripts/deployment/deploy_env/testnets/juno.env
scripts/deployment/deploy_liquidity_hub.sh

Juno testnet uni-3 was shut down. uni-5 is the latest one, so this fixes the deployment script.
---

ci: add uni-5 to deployment script

---

Cargo.lock
contracts/liquidity_hub/vault-network/vault_factory/Cargo.toml
contracts/liquidity_hub/vault-network/vault_factory/schema/execute_msg.json
contracts/liquidity_hub/vault-network/vault_factory/src/contract.rs
contracts/liquidity_hub/vault-network/vault_factory/src/err.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/mod.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/remove_vault.rs
packages/vault-network/src/vault_factory.rs

This PR adds a message on the vault factory contract to remove vaults added to the vault directory. This way, in case wrong vaults are added, they can be removed and keep the vault directory clean.
Implemented `ExecuteMsg::RemoveVault` in a slightly different way than requested in [Issue #52](https://github.com/White-Whale-Defi-Platform/migaloo-core/issues/52):
I decided to use AssetInfo instead of the vault address as vault identifier because AssetInfo is the key for the Vaults Map.
#52 
---

feat: remove vaults from vault factory

---

Cargo.lock
contracts/liquidity_hub/vault-network/vault_factory/Cargo.toml
contracts/liquidity_hub/vault-network/vault_factory/src/contract.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/create_vault.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/migrate_vaults.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/remove_vault.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/update_config.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/update_vault_config.rs

This PR optimizes the owner validation in the vault factory contract by moving it to the execute entry point instead of having it on each function triggered as described in [Issue #78](https://github.com/White-Whale-Defi-Platform/migaloo-core/issues/78)
#78 
---

refactor: owner validation for vault factory contract

---

.github/workflows/ci-test-fmt-check.yaml
.github/workflows/pr-convcom-check.yaml
Cargo.lock
Cargo.toml
contracts/liquidity_hub/fee_collector/Cargo.toml
contracts/liquidity_hub/vault-network/vault/Cargo.toml
contracts/liquidity_hub/vault-network/vault/schema/execute_msg.json
contracts/liquidity_hub/vault-network/vault/schema/query_msg.json
contracts/liquidity_hub/vault-network/vault_factory/Cargo.toml
contracts/liquidity_hub/vault-network/vault_router/Cargo.toml
contracts/liquidity_hub/vault-network/vault_router/schema/execute_msg.json
packages/terraswap/Cargo.toml
packages/vault-network/Cargo.toml
packages/white-whale/Cargo.toml

Uses the newly released Rust workspaces feature to manage the dependencies across the repository. Additionally, the `publish = false` flag is added to a few core contracts, as we do not want to upload contracts to crates.io
Closes #84
Currently blocked by White-Whale-Defi-Platform/pool-network#12
---
_Note that Cargo is current complaining about a few 1.64 issues_

Use Rust 1.64 workspaces

---

Cargo.lock
contracts/liquidity_hub/pool-network/terraswap_factory/Cargo.toml
contracts/liquidity_hub/pool-network/terraswap_factory/schema/terraswap-factory.json
contracts/liquidity_hub/pool-network/terraswap_factory/src/commands.rs
contracts/liquidity_hub/pool-network/terraswap_factory/src/contract.rs
contracts/liquidity_hub/pool-network/terraswap_factory/src/testing.rs
packages/terraswap/src/factory.rs

This adds the possibility to update a pair config from the factory, which is the only way to do it since only the owner of a pair can perform this action.
Did integration tests directly on testnet.
---

feat: add message to update pair config to pool factory

---

.gitignore
scripts/check_artifacts_size.sh
scripts/deployment/deploy_env/chain_env.sh
scripts/deployment/deploy_env/testnets/local.env
scripts/deployment/deploy_liquidity_hub.sh
scripts/deployment/deploy_pool.sh
scripts/deployment/deploy_vault.sh
scripts/deployment/wallet_importer.sh

This PR fixes #82. It is  now possible to deploy WW liquidity hubs totally, partially or just specific contracts.
It also includes a script to create vaults and pools!
#82
---

Scripts improvements

---

Cargo.lock
contracts/liquidity_hub/pool-network/terraswap_factory/Cargo.toml
contracts/liquidity_hub/pool-network/terraswap_factory/schema/terraswap-factory.json
contracts/liquidity_hub/pool-network/terraswap_factory/src/commands.rs
contracts/liquidity_hub/pool-network/terraswap_factory/src/contract.rs
contracts/liquidity_hub/pool-network/terraswap_factory/src/testing.rs
packages/terraswap/src/factory.rs

This PR fixes broken remove pair message from the pool factory, preventing from effectively removing an existing pair.
---

fix: remove pair message fix on pool factory

---

scripts/deployment/deploy_pool.sh
scripts/deployment/deploy_vault.sh

Creating pools and vaults require providing a burn fee now. This PR fixes that on the deployment scripts. 
---

ci: add burn fee to vault and pool deployment scripts

---

scripts/deployment/deploy_pool.sh

This PR fixes the deploy_pool.sh script.
---

chore: fix deploy pool script to add right denom decimal places

---

contracts/liquidity_hub/pool-network/terraswap_pair/src/commands.rs
contracts/liquidity_hub/pool-network/terraswap_pair/src/helpers.rs
contracts/liquidity_hub/pool-network/terraswap_pair/src/tests/testing.rs

The slippage tolerance when adding liquidity is using a simple ratio, which does not apply with the stableswap algorithm.  The amp factor needs to be considered here.
#131
https://github.com/White-Whale-Defi-Platform/white-whale-core/pull/131/commits/596bb43fab6fa6ed90419c3ed2cbbcef48ef96ee
---

fix: include amp factor when calculating slippage on stableswap

---

contracts/liquidity_hub/fee_distributor/src/state.rs

This PR implements a fix for an edge case on the fee distributor, causing errors when trying to claim rewards from expired epochs.
---

fix(fee_distributor): fix edge case where the contract would error due to expired epochs becoming claimable

---

Cargo.lock
contracts/liquidity_hub/fee_distributor/Cargo.toml
contracts/liquidity_hub/whale_lair/Cargo.toml
contracts/liquidity_hub/whale_lair/src/state.rs

This PR tweaks the weight calculation on the bonding contract, making it 0 on the initial bonding.
---

fix: tweak weight calculation on bonding contract

---

contracts/liquidity_hub/pool-network/stableswap_3pool/src/tests/withdrawals.rs
contracts/liquidity_hub/pool-network/terraswap_pair/src/tests/provide_liquidity.rs
contracts/liquidity_hub/pool-network/terraswap_pair/src/tests/testing.rs
contracts/liquidity_hub/pool-network/terraswap_pair/src/tests/withdrawals.rs

It was just a missing import? Also clean up lints in pool-network while at it
Seen this coming up in my console while refactoring bonding, did as a separate PR.

fix(3pool): Fix broken test on main

---

contracts/liquidity_hub/pool-network/incentive_factory/schema/incentive-factory.json
contracts/liquidity_hub/pool-network/incentive_factory/schema/raw/execute.json
contracts/liquidity_hub/pool-network/incentive_factory/src/contract.rs
contracts/liquidity_hub/pool-network/incentive_factory/src/execute/update_config.rs
packages/white-whale/src/pool_network/incentive_factory.rs

This adds the possibility to change the fee distributor address on the incentive factory.
---

chore: add fee distributor address to update_config message on incetive factory

---

Cargo.lock
contracts/liquidity_hub/fee_collector/src/tests/integration.rs
contracts/liquidity_hub/whale_lair/Cargo.toml
contracts/liquidity_hub/whale_lair/src/commands.rs
contracts/liquidity_hub/whale_lair/src/contract.rs
contracts/liquidity_hub/whale_lair/src/error.rs
contracts/liquidity_hub/whale_lair/src/helpers.rs

This PR prevents users from bonding/unbonding if the latest epoch has not been created yet after it was supposed to be created. That fixes potential issues with global index snapshots.
---

fix: prevent users from bonding/unbonding if the latest epoch has not been created

---

contracts/liquidity_hub/vault-network/vault_factory/src/contract.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/create_vault.rs

This fixes missing funds being passed to the vault when using the token factory to create the lp denom.
---

fix: add missing funds to create_vault message so the tf denom can be created

---

Cargo.lock
contracts/liquidity_hub/pool-network/incentive/Cargo.toml
contracts/liquidity_hub/pool-network/incentive/src/queries/get_rewards.rs
contracts/liquidity_hub/pool-network/incentive/src/tests/integration.rs
contracts/liquidity_hub/vault-network/vault_factory/src/execute/create_vault.rs

This PR improves the incentive rewards query by filtering the zero amount rewards. Instead, it returns an empty vector. 
#212 
---

fix(incentive): filter zero rewards from query

---

Cargo.lock
contracts/liquidity_hub/pool-network/incentive_factory/Cargo.toml
contracts/liquidity_hub/pool-network/incentive_factory/schema/incentive-factory.json
contracts/liquidity_hub/pool-network/incentive_factory/schema/raw/execute.json
contracts/liquidity_hub/pool-network/incentive_factory/src/contract.rs
contracts/liquidity_hub/pool-network/incentive_factory/src/execute/migrate_incentive.rs
contracts/liquidity_hub/pool-network/incentive_factory/src/execute/mod.rs
packages/white-whale/src/pool_network/incentive_factory.rs

This PR improves the migrate incentive message on the incentive factory, so multiple incentives can be migrated at once. This saves the headache of needing to send multiple messages to migrate all the incentives created by a factory.
---

chore: make it possible to migrate multiple incentive contracts at once

---

Cargo.lock
contracts/liquidity_hub/pool-network/incentive/Cargo.toml
contracts/liquidity_hub/pool-network/incentive/schema/incentive.json
contracts/liquidity_hub/pool-network/incentive/schema/raw/execute.json
contracts/liquidity_hub/pool-network/incentive/schema/raw/query.json
contracts/liquidity_hub/pool-network/incentive/schema/raw/response_to_flow.json
contracts/liquidity_hub/pool-network/incentive/schema/raw/response_to_flows.json
contracts/liquidity_hub/pool-network/incentive/src/claim.rs
contracts/liquidity_hub/pool-network/incentive/src/contract.rs
contracts/liquidity_hub/pool-network/incentive/src/error.rs
contracts/liquidity_hub/pool-network/incentive/src/execute/close_flow.rs
contracts/liquidity_hub/pool-network/incentive/src/execute/expand_flow.rs
contracts/liquidity_hub/pool-network/incentive/src/execute/mod.rs
contracts/liquidity_hub/pool-network/incentive/src/execute/open_flow.rs
contracts/liquidity_hub/pool-network/incentive/src/helpers.rs
contracts/liquidity_hub/pool-network/incentive/src/migrations.rs
contracts/liquidity_hub/pool-network/incentive/src/queries/get_flow.rs
contracts/liquidity_hub/pool-network/incentive/src/queries/get_flows.rs
contracts/liquidity_hub/pool-network/incentive/src/queries/get_rewards.rs
contracts/liquidity_hub/pool-network/incentive/src/tests/helpers.rs
contracts/liquidity_hub/pool-network/incentive/src/tests/integration.rs
contracts/liquidity_hub/pool-network/incentive/src/tests/mod.rs
contracts/liquidity_hub/pool-network/incentive/src/tests/suite.rs
packages/white-whale/src/pool_network/incentive.rs

This PR adds the functionality to expand an active incentive flow.
---

feat: flow expansion

---

Cargo.lock
contracts/liquidity_hub/pool-network/terraswap_pair/src/contract.rs
contracts/liquidity_hub/vault-network/vault/Cargo.toml
scripts/build_release.sh

This PR increments the vault contract version so we can migrate it on terra once we compile with the new token (osmosis) factory.
---

chore: bump vault contract version before migration on terra

---

Cargo.lock
contracts/liquidity_hub/fee_collector/Cargo.toml
contracts/liquidity_hub/fee_collector/schema/fee_collector.json
contracts/liquidity_hub/fee_collector/schema/raw/execute.json
contracts/liquidity_hub/fee_collector/src/commands.rs
contracts/liquidity_hub/fee_collector/src/contract.rs
contracts/liquidity_hub/fee_collector/src/queries.rs
contracts/liquidity_hub/fee_collector/src/state.rs
contracts/liquidity_hub/fee_collector/src/tests/integration.rs
contracts/liquidity_hub/fee_collector/src/tests/testing.rs
packages/white-whale/src/fee_collector.rs

This PR makes the fee aggregation permissionless on the fee collector contract.
---

chore: make fee aggregation permissionless

---

scripts/build_release.sh
scripts/build_schemas.sh
scripts/check_artifacts_size.sh
scripts/get_artifacts_versions.sh

This PR adds a script to the CI suite to get the contract versions in the project.
---

ci: add script to get contract versions

---

scripts/deployment/extract_pools.sh

This script is a utility to extract the pool information from the pool factory.
---

ci: add script to extract pool information

---

scripts/deployment/deploy_vault.sh

This PR fixes the script for vault deployment.
---

ci: fix script for vault deployment

---

Cargo.lock
contracts/liquidity_hub/pool-network/terraswap_factory/Cargo.toml
contracts/liquidity_hub/pool-network/terraswap_factory/src/commands.rs
contracts/liquidity_hub/pool-network/terraswap_factory/src/contract.rs
contracts/liquidity_hub/pool-network/terraswap_factory/src/testing.rs

This PR removes the add_native_decimals balance check, since the pool factory is permissioned there's no risk on this one. Also, this change will allow allowing another wallet to create pools via authz without the need to send any balances to the contract.
---

chore: remove add_native_decimals balance check

---

.github/workflows/release-artifacts-on-tag.yaml

This PR removes the custom token factory release builds  from the ci release script for the docker images used by the release script are not available in the docker hub.
---

ci: fix release action

---

scripts/build_release.sh

This PR adds the osmosis chain flag on the build_release script.
---

ci: add osmosis chain to release script

---

.github/PULL_REQUEST_TEMPLATE.md
docs/CONTRIBUTING.md

This PR resolves three issues with the contributing guide
- PR template references a dead link
- contributing guide does not mention the need for PyO3 installation
- contributing guide does not reference a step to regenerate Protobuf schemas if needed
---

Fix broken links in contributing guide and reference extra steps required

---

.github/workflows/release-artifacts-on-tag.yaml
scripts/build_release.sh

This adds the vanilla flavor of white whale to the release_build script, which builds without any feature flag.
---

ci: add vanilla variant to build release script for ci

---

scripts/deployment/deploy_env/base.env
scripts/deployment/deploy_env/base_injective.env
scripts/deployment/deploy_env/base_migaloo.env
scripts/deployment/deploy_env/chain_env.sh
scripts/deployment/deploy_env/mainnets/osmosis.env
scripts/deployment/deploy_liquidity_hub.sh

This PR tweaks some of the env variable values. Also adds the osmosis.env to mainnets.
---

ci: tweak env variables

---

packages/white-whale-std/Cargo.toml

This fixes the link for the white-whale-std docs on crates.io
---

ci: fix doc link on white-whale-std

---

Cargo.toml

This PR forces the protobuf version to be exactly 3.2.0 to avoid issues with other dependencies trying to pull a different (higher) version. 
---

chore: forces the protobuf version to be 3.2.0

---

justfile
scripts/hooks/commit-msg.sh
scripts/hooks/pre-commit.sh

This PR improves the pre-commit hook, formatting not only rust files but also toml and shell scripts files. 
It also introduces a commit-msg hook, which makes sure the conventional commit format is being used. 
---

ci: improve pre-commit hook

---

Cargo.lock
contracts/liquidity_hub/pool-network/terraswap_factory/Cargo.toml

To include the newly added cosmwasm_interface_contract param when updating pair configs on osmosis.
---

fix: bump pool factory version

---

docs/CONTRIBUTING.md

In #274 we introduced an env loader for the CLI to simplify and unify our commands used in the repository. This commit documents the usage of the `just` command runner for new users of the repository.
---

Document usage of just command line runner

---

contracts/liquidity_hub/vault-network/vault/src/contract.rs
contracts/liquidity_hub/vault-network/vault/src/migrations.rs

The vault contained a state migration to a version that it was already migrated in all satellite markets, thus the migration was failing. Removing unnecessary state migration. 
---

fix: broken vault state migration

---

.github/workflows/release-artifacts-on-tag.yaml

This should:
Allow us to pass the artifact versions.txt and have it appended to the generated release notes https://github.com/softprops/action-gh-release/blob/4634c16e79c963813287e889244c50009e7f0981/src/github.ts#L244
---

fix: Add input append_body and generate_release_notes, set both to true

---

Cargo.lock
contracts/liquidity_hub/vault-manager/Cargo.toml
contracts/liquidity_hub/vault-manager/tests/common/suite.rs
packages/white-whale-std/Cargo.toml
packages/white-whale-std/src/lib.rs
packages/white-whale-std/src/tokenfactory/common.rs
packages/white-whale-testing/Cargo.toml
packages/white-whale-testing/README.md
packages/white-whale-testing/src/lib.rs
packages/white-whale-testing/src/multi_test/mod.rs
packages/white-whale-testing/src/multi_test/stargate_mock.rs

Moves the Osmosis mocking to the `white-whale-testing` package, rather than `white-whale-std` package. This lets us drop the `#[cfg(test)]` qualifiers which restrict integration tests from consuming our package.
This is a suitable restriction to drop, since it is likely that any code that is using `white-whale-testing` is performing testing operations, while our `white-whale-std` was public facing.
Fixing such issue is necessary, as we currently cannot `cargo test` on the `release/v2_contracts` branch.
---

Reorganize testing modules

---

contracts/liquidity_hub/pool-manager/schema/pool-manager.json
contracts/liquidity_hub/pool-manager/schema/raw/execute.json
contracts/liquidity_hub/pool-manager/schema/raw/response_to_pair.json
contracts/liquidity_hub/pool-manager/src/contract.rs
contracts/liquidity_hub/pool-manager/src/manager/commands.rs
contracts/liquidity_hub/pool-manager/src/tests/integration_tests.rs
contracts/liquidity_hub/pool-manager/src/tests/suite.rs
packages/white-whale-std/src/pool_manager.rs

This PR removes balances from `PairInfo`, as it doesn't provide any value. The balances are being held in assets already.
The previous branch, `release/v2_contracts`, had a couple of errors that were shown at compile time that are now fixed.
It also fixes the `pool-manager` tests that were not passing.
#307 
---

fix(smart-contracts): remove balances from PairInfo & fix minor errors

---

contracts/liquidity_hub/pool-manager/src/router/commands.rs
contracts/liquidity_hub/pool-manager/src/swap/commands.rs
contracts/liquidity_hub/pool-manager/src/tests/integration_tests.rs

We currently use `BankMsg::Send` when a swap has occurred to send the protocol fees to the whale-lair. This is not desired, as it does not allow the whale-lair contract to hook into receiving the assets.
Closes #312.
Adding a integration test for this behaviour this is hard due to https://github.com/CosmWasm/cw-plus/issues/763. Unfortunately the cosmwasm team is not interested in addressing this issue.
---

Send protocol fees from pool manager via FillRewards rather than BankMsg

---

Cargo.lock
Cargo.toml
packages/white-whale-std/Cargo.toml

This PR bumps white-whale-std and makes the project pull the version from crates.io.
---

fix: bump white-whale-std and make the main Cargo.toml pull from cratees.io

---

contracts/liquidity_hub/pool-manager/schema/pool-manager.json
contracts/liquidity_hub/pool-manager/schema/raw/response_to_pair.json
contracts/liquidity_hub/pool-manager/src/contract.rs
contracts/liquidity_hub/pool-manager/src/queries.rs
contracts/liquidity_hub/pool-manager/src/tests/integration_tests.rs
contracts/liquidity_hub/pool-manager/src/tests/suite.rs
packages/white-whale-std/src/pool_manager.rs

Adds the total LP share amount to the Pair query response, as this was a missing piece of information lost when we removed the `Pool` query. 
Closes [#344](https://github.com/White-Whale-Defi-Platform/white-whale-core/issues/344)
---

chore: add total LP share amount to the Pair query response

---

contracts/liquidity_hub/pool-manager/src/helpers.rs
contracts/liquidity_hub/pool-manager/src/swap/perform_swap.rs
contracts/liquidity_hub/pool-manager/src/tests/integration_tests.rs

This is an issue we solved in the past in V1, but somehow was lingering in V2.
---

fix: pool-manager max spread assertion

---

contracts/liquidity_hub/pool-manager/schema/pool-manager.json
contracts/liquidity_hub/pool-manager/schema/raw/execute.json
contracts/liquidity_hub/pool-manager/src/contract.rs
contracts/liquidity_hub/pool-manager/src/error.rs
contracts/liquidity_hub/pool-manager/src/helpers.rs
contracts/liquidity_hub/pool-manager/src/liquidity/commands.rs
contracts/liquidity_hub/pool-manager/src/manager/commands.rs
contracts/liquidity_hub/pool-manager/src/queries.rs
contracts/liquidity_hub/pool-manager/src/state.rs
contracts/liquidity_hub/pool-manager/src/swap/commands.rs
contracts/liquidity_hub/pool-manager/src/swap/perform_swap.rs
contracts/liquidity_hub/pool-manager/src/tests/integration_tests.rs
contracts/liquidity_hub/pool-manager/src/tests/suite.rs
contracts/liquidity_hub/pool-manager/src/tests/unit_tests/swap.rs
packages/white-whale-std/src/pool_manager.rs

Enables single-side liquidity provision. Closes #310 
---

feat: single-side liquidity provision

---

contracts/liquidity_hub/epoch-manager/README.md

This PR adds a readme file explaining how the epoch manager works.
---

docs(epoch-manager): add readme to epoch manager

---

Cargo.lock
contracts/liquidity_hub/fee_distributor/Cargo.toml
contracts/liquidity_hub/fee_distributor/src/commands.rs
contracts/liquidity_hub/fee_distributor/src/error.rs

This PR makes the fee distributor use `checked_mul_floor` when calculating rewards to be distributed. This might fix the issue some users have when claiming rewards.
---

fix: fee distributor claim floor fix

---

contracts/liquidity_hub/bonding-manager/schema/bonding-manager.json
contracts/liquidity_hub/bonding-manager/schema/raw/execute.json
contracts/liquidity_hub/bonding-manager/src/bonding/commands.rs
contracts/liquidity_hub/bonding-manager/src/contract.rs
contracts/liquidity_hub/bonding-manager/src/helpers.rs
contracts/liquidity_hub/bonding-manager/src/state.rs
contracts/liquidity_hub/bonding-manager/src/tests/bond.rs
contracts/liquidity_hub/bonding-manager/src/tests/claim.rs
contracts/liquidity_hub/bonding-manager/src/tests/queries.rs
contracts/liquidity_hub/bonding-manager/src/tests/suite.rs
contracts/liquidity_hub/bonding-manager/src/tests/unbond_withdraw.rs
packages/white-whale-std/src/bonding_manager.rs

This PR improves the validation when bonding/unbonding so it makes sure not only that a new epoch has been created but that the system is up to date, i.e. if an epoch is due to be created the contract won't let you bond or unbond. 
---

fix(bonding_manager): fix validation of epoch when bonding/unbonding

---

Cargo.lock
contracts/liquidity_hub/bonding-manager/schema/bonding-manager.json
contracts/liquidity_hub/bonding-manager/schema/raw/response_to_config.json
contracts/liquidity_hub/bonding-manager/src/contract.rs
contracts/liquidity_hub/bonding-manager/src/helpers.rs
contracts/liquidity_hub/pool-manager/schema/pool-manager.json
contracts/liquidity_hub/pool-manager/schema/raw/query.json
contracts/liquidity_hub/pool-manager/schema/raw/response_to_pools.json
contracts/liquidity_hub/pool-manager/src/contract.rs
contracts/liquidity_hub/pool-manager/src/manager/commands.rs
contracts/liquidity_hub/pool-manager/src/queries.rs
contracts/liquidity_hub/pool-manager/src/tests/integration_tests.rs
contracts/liquidity_hub/pool-manager/src/tests/suite.rs
integration-tests/tests/common/suite.rs
packages/white-whale-std/Cargo.toml
packages/white-whale-std/src/pool_manager.rs

This PR modifies the `Pool` query on the pool manager so that it returns a list of pools if desired. This can help frontends list all the pools in the contract. It offers pagination.
---

feat(pool_manager): pools query improvement

---

Cargo.lock
Cargo.toml
contracts/liquidity_hub/bonding-manager/Cargo.toml
contracts/liquidity_hub/bonding-manager/src/error.rs
contracts/liquidity_hub/epoch-manager/Cargo.toml
contracts/liquidity_hub/epoch-manager/src/error.rs
contracts/liquidity_hub/incentive-manager/Cargo.toml
contracts/liquidity_hub/incentive-manager/src/error.rs
contracts/liquidity_hub/pool-manager/Cargo.toml
contracts/liquidity_hub/pool-manager/src/error.rs
contracts/liquidity_hub/vault-manager/Cargo.toml
contracts/liquidity_hub/vault-manager/src/error.rs

This PR uses the macro from https://crates.io/crates/cw-migrate-error-derive to generate the previous `MigrateInvalidVersion` across all the V2 contracts.
---

refactor: uses procedural macro to replace the MigrateInvalidVersion on V2 contracts

---

Cargo.lock
contracts/liquidity_hub/fee_collector/Cargo.toml

Version bump for the fee collector after simulation aggregation fix in #378 .
---

chore(fee_collector): bump contract version

---

Cargo.lock
contracts/liquidity_hub/pool-network/incentive/Cargo.toml
contracts/liquidity_hub/pool-network/incentive/src/execute/withdraw.rs

This PR unlocks the LPs from incentive contracts.
---

chore: unlock LPs from incentives
